embedder:
  provider: "ollama"
  config:
    model: "nomic-embed-text"
    dimension: 384

long_term_memory:
  enabled: true
  external: true
  connection_string: "postgresql://user:pass@host:5432/db"
