active_provider: "ollama"
storage_path: "./data/memory"
embedder:
  model: "nomic-embed-text"
  dimension: 384
providers:
  - name: ollama
    enabled: true

long_term_memory:
  enabled: true
  external: true
  connection_string: "postgresql://user:pass@host:5432/db"
